import nodemailer from 'nodemailer';

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.SMTP_PORT) || 587,
  secure: false,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

export async function sendSummaryEmail(toEmail, toName, meeting, summaryHtml) {
  const subject = `Meeting notes: ${meeting.subject || 'Your meeting'}`;
  const date = new Date(meeting.start_time).toLocaleDateString('en-IN', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f5f5f5; margin: 0; padding: 20px; }
  .container { max-width: 640px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
  .header { background: #0f172a; padding: 28px 32px; }
  .header h1 { color: white; margin: 0; font-size: 22px; font-weight: 600; }
  .header p { color: #94a3b8; margin: 6px 0 0; font-size: 14px; }
  .badge { display: inline-block; background: #22c55e; color: white; font-size: 11px; font-weight: 600; padding: 2px 8px; border-radius: 20px; margin-left: 8px; vertical-align: middle; }
  .body { padding: 28px 32px; }
  .meta { background: #f8fafc; border-radius: 8px; padding: 16px 20px; margin-bottom: 24px; font-size: 14px; color: #475569; line-height: 1.8; }
  h3 { font-size: 15px; font-weight: 600; color: #0f172a; margin: 24px 0 10px; border-left: 3px solid #6366f1; padding-left: 10px; }
  ul { margin: 0; padding-left: 20px; }
  li { font-size: 14px; color: #334155; line-height: 1.7; margin-bottom: 4px; }
  li strong { color: #0f172a; }
  .footer { background: #f8fafc; padding: 20px 32px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; text-align: center; }
  .footer a { color: #6366f1; text-decoration: none; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>MeetSense <span class="badge">AI Notes</span></h1>
    <p>${meeting.subject || 'Meeting'} &middot; ${date}</p>
  </div>
  <div class="body">
    ${summaryHtml}
  </div>
  <div class="footer">
    <p>Generated by <a href="${process.env.APP_URL}">MeetSense</a> &mdash; your open-source AI meeting assistant</p>
    <p><a href="${process.env.APP_URL}/dashboard">View in dashboard</a> &middot; <a href="${process.env.APP_URL}/unsubscribe">Unsubscribe</a></p>
  </div>
</div>
</body>
</html>`;

  await transporter.sendMail({
    from: process.env.EMAIL_FROM,
    to: toEmail,
    subject,
    html,
  });
}

export async function sendWelcomeEmail(toEmail, toName) {
  await transporter.sendMail({
    from: process.env.EMAIL_FROM,
    to: toEmail,
    subject: 'Welcome to MeetSense — your meetings will never be the same',
    html: `<p>Hi ${toName || 'there'},</p>
    <p>You're all set! MeetSense will now automatically join your Teams meetings, take notes, and email you a summary.</p>
    <p>No action needed — just have your meetings as usual. The bot will appear as "<strong>${process.env.BOT_NAME || 'MeetSense Notetaker'}</strong>" in the participant list.</p>
    <p><a href="${process.env.APP_URL}/dashboard">View your dashboard →</a></p>`,
  });
}
